#!c:\users\ruth\desktop\csa2025\group5_predicting_high_risk_taxpayers_using_ml\njoki\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
